### ISSUE TITLE
very interesting project!

### ISSUE THREAD

**Issue by OfekShochat** [khonsulabs/bonsaidb#130]
hello! I'm very interested in this project. seems like a good one! when will bonsaidb be able to be stable?

**Comment by ecton** [comment]
Thank you for asking! It depends on your definition of stable. We're about to remove the experimental label and release an alpha to crates.io. While I've done a lot of testing personally, and there is a fairly extensive unit test suite, I want early adopters to be cautious and backup their data frequently.

We're going to prioritize stability over features during the alpha phase, but until we have additional users, it's hard to offer any guarantee of stability.

I'm hopeful that a version without replication will be considered stable within the next 3-6 months, but it will depend on how smoothly the alpha process is for early adopters.

**Comment by OfekShochat** [comment]
ok, thank you! maybe you should have issues with milestones to reach being stable. Id be interested in following the development

**Comment by ecton** [comment]
Thank you for the suggestion -- I've gone ahead and created this issue that you could follow if you want updates as we work towards stability: https://github.com/khonsulabs/bonsaidb/issues/137

Part of becoming stable is a little like the chicken-and-egg problem. It's hard to feel like the product is stable without enough users testing it, and it's a tough sell to get developers to adopt it when it isn't stable! :) We will get there, and hopefully without any users losing any data along the way!

Thank you again for the kind words and checking out the project!
