### ISSUE TITLE
Document restrictions for CollectionName

### ISSUE THREAD

**Issue by ModProg** [khonsulabs/bonsaidb#143]
I tried to use an underscore, but those are apparently not allowed.

Would also be interested to know why?

**Comment by ecton** [comment]
The requirements are currently documented on [Name](https://dev.bonsaidb.io/main/bonsaidb/core/schema/struct.Name.html), but as you rightfully note, should definitely be either linked to or included on all the types that use it.

> Would also be interested to know why?

In short, I wanted to reserve characters for internal use, and those two are `.` and `_`. There are only so many characters that are safe for the filesystem. I suppose we could escape unsafe characters now that I'm writing that... I might end up doing that and removing almost all name restrictions.

Great feedback.

**Comment by ModProg** [comment]
Alright, I'd add whatever restrictions will be there in the end to the derive macro as well so that they'll be a compile time error.

**Comment by ecton** [comment]
I've made up my mind to remove all restrictions this morning. I'll reference this issue from the commit when I push it.
