### ISSUE TITLE
Add `encryption_key` to Collection derive

### ISSUE THREAD

**Issue by ecton** [khonsulabs/bonsaidb#181]
Didn't think of it in #138, but the encryption_key function should also be derivable:

```rust
#[derive(Collection)]
#[collection(..., encryption_key = Some(KeyId::Master))]
struct MyCollection {...}
``` 

should implement the encryption key method in the generated Collection implementation:

```rust
impl Collection for MyCollection {
    // ...
    fn encryption_key() -> Option<KeyId> {
        Some(KeyId::Master)
    }
}
```

It may also be nice to support allowing the encryption key to be None when it is disabled. Perhaps a second parameter `allow_unencrypted_storage` (feel free to suggest alternative names) which changes the implementation to:

```rust
impl Collection for MyCollection {
    // ...
    fn encryption_key() -> Option<KeyId> {
        if ENCRYPTION_ENABLED {
            Some(KeyId::Master)
        } else {
            None
        }
    }
}
```

**Comment by ModProg** [comment]
> t may also be nice to support allowing the encryption key to be None when it is disabled. Perhaps a second parameter allow_unencrypted_storage (feel free to suggest alternative names) which changes the implementation to:
> ```rs
> impl Collection for MyCollection {
>     // ...
>     fn encryption_key() -> Option<KeyId> {
>         if ENCRYPTION_ENABLED {
>             Some(KeyId::Master)
>         } else {
>             None
>         }
>     }
> }
> ```

What is `ENCRYPTION_ENABLED` here? I would make the flag `allow_unencrypted_storage` maybe reflect what `ENCRYPTION_ENABLED` is.

For syntax here:
> ```rs
> #[derive(Collection)]
> #[collection(..., encryption_key = Some(KeyId::Master))]
> struct MyCollection {...}
> ```

We could also use `encryption_key = KeyId::Master` and wrap it in `Some()` internally, but that would make it impossible to give it a function reference returning an Option, so probably we should stay with your proposed syntax.

**Comment by ecton** [comment]
> What is `ENCRYPTION_ENABLED` here? I would make the flag `allow_unencrypted_storage` maybe reflect what `ENCRYPTION_ENABLED` is.

https://docs.rs/bonsaidb/latest/bonsaidb/core/constant.ENCRYPTION_ENABLED.html

> We could also use `encryption_key = KeyId::Master` and wrap it in `Some()` internally, but that would make it impossible to give it a function ~reference~ call returning an Option, so probably we should stay with your proposed syntax.

I wondered whether to make encryption_key = None be implied and Some() always be set. I honestly didn't even consider the idea you came up with -- but that is a valid reason to keep the syntax I suggested. But honestly, I don't know if that would be a use case that's worth supporting. I originally suggested it because it seemed easier to handle the logic in my head :)

> This would finally give my `Expression` type a use, as we could just put what ever we are given directly into the expansion.

Well that seems a good enough reason to stick with Option anyways :) Honestly, your call though -- I am attracted the brevity of not having to specify Some(), but you did bring up a valid use case too.

**Comment by ModProg** [comment]
so the logic:
```rs
if encryption_required || !encryption_optional || ENCRYPTION_ENABELED {
    encryption_key
} else {
    None
}
```

**Comment by ModProg** [comment]
> Yes, that logic is correct (assuming it's only applied if encryption_key is set). I would write it as `encryption_required || (encryption_optional && ENCRYPTION_ENABLED)` because my brain processes that easier, but they're equivalent.

Well in your logic if encryption_optional was false but ENCRYPTION_ENABLED true, it would not encrypt. Is that what you meant?

**Comment by ecton** [comment]
You're right with the original logic. I should have written up the truth table.
