### ISSUE TITLE
Add `rust-version` to manifests

### ISSUE THREAD

**Issue by daxpedda** [khonsulabs/bonsaidb#199]
We didn't deal with MSRV yet. First we should probably note in the README our MSRV policy, which is currently that we don't care about it, as far as I know.

Next we should add the `rust-version` field to all Cargo manifests to prevent consumers from dealing with unhelpful compile-errors. Currently we require at least 1.58 because of https://github.com/ModProg/attribute-derive. Which is an issue somebody already encountered.

**Comment by ecton** [comment]
Where is `rustversion` documented? I'm trying to find any way to do this and every link I click says nothing is currently implemented except using a build.rs script.

**Comment by daxpedda** [comment]
I accidentally used `rustversion` instead of `rust-version`, https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field.
