### ISSUE TITLE
Leverage tikv as KV store

### ISSUE THREAD

**Issue by huiwenhan** [khonsulabs/bonsaidb#202]
Why not leverage TIkv as the KV store to accelerate the bonsainDB development ?
https://github.com/tikv/tikv

**Comment by daxpedda** [comment]
I don't believe TiKV aligns with BonsaiDBs goals. Please correct me if I'm wrong with any of my assumptions here, I never used TiKV and only have a very high-level undderstanding of it:
- Not a library and can't be or isn't intended to be used as such.
- Heavily depends on C++ codebases.
- Massive list of dependencies that can't be toggled by crate features.

These are just some fundamentals that I believe don't align.

**Comment by ecton** [comment]
Additionally, TiKV [requires a lot](https://tikv.org/docs/5.1/deploy/install/prerequisites/) more than BonsaiDb. The biggest issue to me, aside from the ones that Daxpedda raised, is that there is no way to use TiKV in a non-networked mode or single-server, which is a fundamental feature that BonsaiDb supports.

BonsaiDb's clustering and replication are still to-be-developed. If you need a clustered key-value storage or key-value storage that is considered stable, use TiKV today. If you're looking for the best developer experience for developing and deploying a database that will eventually support clustering as well, BonsaiDb is a good option.

If you're looking for specific features that TiKV has that BonasiDb currently doesn't, please open up issues with specific feature requests.
