### ISSUE TITLE
Add Derive for Api

### ISSUE THREAD

**Issue by ecton** [khonsulabs/bonsaidb#235]
The Api trait should be deriveable:

```rust
struct MyType;

impl Api for MyType {
  type Response = OtherType;
  type Error = bonsaidb::core::api::Infallible;

  fn name() -> ApiName {
    ApiName::new("authority", "name")
  }
}
```

Should be able to be derived as:

```rust
#[derive(Api)]
#[api(authority = "authority", name = "name", response = OtherType, error = Infallible]
struct MyType;
```

Response is required. Error should be optional. If not specified, it should use `bonsaidb_core::api::Infallible`. Authority can be optional the same way the other derives work.

@ModProg

**Comment by ModProg** [comment]
bonsaidb_core::api::Infallible probably should remember to change that to `!` whenever that comes around :laughing:

**Comment by ecton** [comment]
> probably should remember to change that to `!` whenever that comes around

Only if Serde supports `!` with Serialize/Deserialize, which I don't anticipate. That's [the primary reason](https://docs.rs/bonsaidb/latest/bonsaidb/core/api/enum.Infallible.html) for having a different type than `std::convert::Infallible` -- due to orphan rules I can't implement Serialize/Deserialize for `std::convert::Infallible`, and similarly, I wouldn't be able to for the never type either.

**Comment by ModProg** [comment]
That makes sense, but when `!` is stabilized, it would probably make sense to ask serde to add an implementation for it again.
