### ISSUE TITLE
File storage format questions

### ISSUE THREAD

**Issue by happysalada** [khonsulabs/bonsaidb#247]
What is the format when the db is stored as a file ? (I couldn't find documentation on it).
Is the format fixed or would there be a possibility for a human readable format ? (json, toml, text, anything).

**Comment by ecton** [comment]
The database is stored using [Nebari](https://github.com/khonsulabs/nebari/). There is no alternate storage format, although the database can be exported using the [`backup()`](https://docs.rs/bonsaidb/latest/bonsaidb/local/struct.Storage.html#method.backup) function. This will export one file per document, using the bytes as stored in the database.

Within the database, the serialization format is completely customizable by the user. The [`bonsaidb::core::document`](https://dev.bonsaidb.io/release/docs/bonsaidb/core/document/index.html) module has some high level information about how this works.

To switch the serialization format from the default ([Pot](https://github.com/khonsulabs/pot) using Serde), it can be customized [on the derive macro](https://dev.bonsaidb.io/release/docs/bonsaidb/core/schema/trait.Collection.html#changing-the-serialization-strategy) or [SerializedCollection](https://dev.bonsaidb.io/release/docs/bonsaidb/core/schema/trait.SerializedCollection.html) can be implemented manually.

**Comment by happysalada** [comment]
Thanks a lot for the detailed answer!

one small detail, the link to transmog on this page https://dev.bonsaidb.io/release/docs/bonsaidb/core/schema/trait.Collection.html#changing-the-serialization-strategy is broken.
(this is not a problem for me at all, I'm just saying to let you know).

**Comment by ecton** [comment]
Thank you for pointing that out! I was attempting to point to a re-export, but even on docs.rs it isn't working correctly. I'll change this to a full link to the repo <https://github.com/khonsulabs/transmog>
