### ISSUE TITLE
Some typos in documentation and README files

### ISSUE THREAD

**Issue by bitcapybara** [khonsulabs/bonsaidb#282]
Hi, I found some typos that confused me a bit:

* In file crates/bonsaidb-local/README.md, line 1:

```markdown
# BonsaiDb Client
```
This should probably be:
```markdown
# BonsaiDb Local
```

* In file crates/bonsaidb-local/src/config.rs, line 326:
```rust
/// Sets [`StorageConfiguration::path`](StorageConfiguration#structfield.memory_only) to true and returns self.
```
This should probably be:
```rust
/// Sets [`StorageConfiguration::memory_only`](StorageConfiguration#structfield.memory_only) to true and returns self.
```

Sorry, I forgot to create an issue before creating PR#281. I have closed that PR and added this issue

**Comment by ecton** [comment]
There wasn't a need to open an issue before submitting such small changes. I really only want an issue/discussion flow when proposing new functionality.

Thank you so much for your help in fixing these!
