### ISSUE TITLE
Build issues on windows with outdated sysinfo/ntapi

### ISSUE THREAD

**Issue by Curstantine** [khonsulabs/bonsaidb#306]
Related cargo [tree](https://pastebin.com/2RyMrDfg), and the [issue](https://pastebin.com/2Zf3fEGZ).

`bonsaidb-local` depends on an outdated version of `sysinfo@v0.23.13` (latest `v0.29.10`) which depends on a now broken `ntapi@v0.3.7` (latest `v0.4.1`).

This issue has existed for awhile now, if issues on stackoverflow is something to go by.

Edit:
This seems to have been fixed by a commit done after the last release. [See](https://github.com/khonsulabs/bonsaidb/commit/2d043544c2de1eb957a93694ad1a3c3ec509ca9f) for an example.
It would be nice to have a version with this issue fixed.

**Comment by ecton** [comment]
I'm hoping to get a new release out shortly. I was hoping for last week but some real life stuff got in the way. It should be this week or next. There shouldn't be any additional breaking changes before the 0.5.0 if you wished to switch to use the main branch in the meantime.

Thank you for using BonsaiDb and reporting this. I'll close this issue once I've released the update.
